#!/bin/zsh

set -euo pipefail

project_root="${0:A:h:h}"
cd "$project_root"

if find . -path './.build*' -prune -o -name '.DS_Store' -print | rg -q '.'; then
    print -u2 "origin audit failed: Finder metadata exists in the source tree"
    exit 1
fi

foreign_pattern='copyright \([cC]\)|copyright ©|copyright [0-9]{4}|all rights reserved|created by|generated by|forked from|ported from|based on|github\.com/|gitlab\.com/|bitbucket\.org/'
if rg -n -i --hidden \
    -g '!.build*/**' \
    -g '!.git/**' \
    -g '!scripts/audit-origin.sh' \
    -g '!LICENSE' \
    "$foreign_pattern" .; then
    print -u2 "origin audit failed: foreign project, attribution, generator, or repository trace found"
    exit 1
fi

if [[ ! -f LICENSE ]] \
    || ! rg -Fqx '# PolyForm Noncommercial License 1.0.0' LICENSE \
    || ! rg -Fqx '## Noncommercial Purposes' LICENSE \
    || ! rg -Fqx 'Required Notice: Copyright 2026 AiWhale980728.' LICENSE; then
    print -u2 "origin audit failed: the standard PolyForm Noncommercial 1.0.0 terms or required notice are missing"
    exit 1
fi

if rg -n 'package\s*\(\s*url:' Package.swift; then
    print -u2 "origin audit failed: third-party Swift package dependency found"
    exit 1
fi

if rg -n '^import ' Sources Tests \
    | rg -v 'import (Foundation|Darwin|RelayCore|Testing)$'; then
    print -u2 "origin audit failed: non-platform or non-project module import found"
    exit 1
fi

print "origin audit passed: no foreign project traces or third-party dependencies"
